### ISSUE TITLE
when gps is disabled, the concentration of nearest station keeps searching

### ISSUE THREAD

**Issue by berntholer** [irceline/aq-mobile-be#49] opened 2018-09-25 15:56 UTC
with gps disabled, the app keeps searching the concentrations of the nearest measurement station (=looping circles), which is of course impossible. the user should get a warning pop-up asking to activate gps or a message should be displayed at the bottom of the screen.

in general I think it is a good idea to not assume the user has it's gps enabled all the time, making detection necessary for all features requiring this.

tested under version `0.4.9`

![image](https://user-images.githubusercontent.com/24441447/46026704-52df9780-c0ec-11e8-8413-627e36a92f67.png)

**Comment by opeeters** [comment] 2018-10-11 07:55
@berntholer can you check whether this persists in 0.5.0 after complete uninstall of the app. I have the suspicion that this related to a change in the format how the location settings are stored. I cannot reproduce..

**Comment by janschulte** [comment] 2018-10-15 13:35
This should also be fixed with: a184b80d5e79c2d31d46228bd61ada0acdbe15d8

**Comment by berntholer** [comment] 2018-10-16 08:43
@opeeters indeed, i completely uninstalled the app and under version 0.5.0 this issue does not appear again, so it seems to be fixed indeed

**Closed** 2018-10-17 09:50 UTC
