### ISSUE TITLE
labels under actual concentrations unclear on main screen

### ISSUE THREAD

**Issue by berntholer** [irceline/aq-mobile-be#41] opened 2018-09-17 08:24 UTC
sometimes the labels under the actual concentrations on the main screen overlap causing garbled text.

as a sidenote, perhaps the whole label text can be shortened. for most users the distance is interesting to know, but the measurement station code + address only for air quality experts?

tested in version `0.4.6` under `android 7.0` 

![screenshot_20180916-093354](https://user-images.githubusercontent.com/24441447/45612561-a2c2bc80-ba63-11e8-9adb-17ee7a1d3064.png)

**Comment by opeeters** [comment] 2018-09-17 08:29
I thought I fixed this issue with 403b37b. But alas. Will give it another shot with next release..

**Comment by opeeters** [comment] 2018-09-25 12:46
@berntholer I cannot reproduce issue. This should be fixed with 0484c1f. Check in release 0.5.0 coming to you soon ;-)

**Closed** 2018-10-17 09:50 UTC
